
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
  labels:
    app: blue-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      labels:
        app: blue-app
    spec:
      containers:
      - name: my-blue-app
        image: adamtravis/rollouts:blue   #deekshithsn/k8s-deployment-strategies
        ports:
        - name: http
          containerPort: 8080
        # env:
        # - name: VERSION
        #   value: v1.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        