apiVersion: v1
kind: Service
metadata:
  name: my-blue-green-app-service
  labels:
    app: my-app
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080

  # Note here that we match both the app and the version
  selector:
    app: green-app