# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-app
#   labels:
#     app: my-app
# spec:
#   replicas: 5
#   selector:
#     matchLabels:
#       app: my-app
#   template:
#     metadata:
#       labels:
#         app: my-app
#         version: v1.0.0
#     spec:
#       containers:
#       - name: my-app
#         image: deekshithsn/k8s-deployment-strategies
#         ports:
#         - name: http
#           containerPort: 8080
#         env:
#         - name: VERSION
#           valueFrom:
#             configMapKeyRef:
#               name: jjtech-cm
#               key: app-version

# --- 

# apiVersion: v1
# kind: Pod
# metadata:
#   name: "myapp"
#   namespace: default
#   labels:
#     app: "myapp"
# spec:
#   containers:
#   - name: myapp
#     image: nginx  # "debian-slim:latest"
#     ports:
#     - containerPort:  80
#       name:  http
#     env:
#     - name: VERSION
#       valueFrom:
#         configMapKeyRef:
#           name: jjtech-cm
#           key: app-version
